In [6]:
!{sys.executable} -m pip install --user numpy
import numpy as np
!{sys.executable} -m pip install --user pandas
import pandas as pd
!{sys.executable} -m pip install --user seadorn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Perceptron

"{sys.executable}" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
"{sys.executable}" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
C:\Users\Nikita\AppData\Local\Temp\ipykernel_4352\2891039674.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
"{sys.executable}" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

In [7]:
data = pd.read_csv('isolet.csv')
data

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f609,f610,f611,f612,f613,f614,f615,f616,f617,class
0,-0.4394,-0.0930,0.1718,0.4620,0.6226,0.4704,0.3578,0.0478,-0.1184,-0.2310,...,0.4102,0.2052,0.3846,0.3590,0.5898,0.3334,0.6410,0.5898,-0.4872,'1'
1,-0.4348,-0.1198,0.2474,0.4036,0.5026,0.6328,0.4948,0.0338,-0.0520,-0.1302,...,0.0000,0.2954,0.2046,0.4772,0.0454,0.2046,0.4318,0.4546,-0.0910,'1'
2,-0.2330,0.2124,0.5014,0.5222,-0.3422,-0.5840,-0.7168,-0.6342,-0.8614,-0.8318,...,-0.1112,-0.0476,-0.1746,0.0318,-0.0476,0.1112,0.2540,0.1588,-0.4762,'2'
3,-0.3808,-0.0096,0.2602,0.2554,-0.4290,-0.6746,-0.6868,-0.6650,-0.8410,-0.9614,...,-0.0504,-0.0360,-0.1224,0.1366,0.2950,0.0792,-0.0072,0.0936,-0.1510,'2'
4,-0.3412,0.0946,0.6082,0.6216,-0.1622,-0.3784,-0.4324,-0.4358,-0.4966,-0.5406,...,0.1562,0.3124,0.2500,-0.0938,0.1562,0.3124,0.3124,0.2188,-0.2500,'3'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7792,-0.6842,-0.3280,-0.1984,0.2956,0.8786,0.8948,0.3118,0.1822,0.1012,0.1740,...,0.7738,0.7738,0.7142,0.6428,0.5952,0.5714,0.3928,0.4286,0.2858,'24'
7793,-0.5912,-0.2420,0.8174,1.0000,0.4642,0.6428,0.6944,0.3056,-0.3888,-0.6826,...,0.1924,-0.1154,0.0192,0.2116,-0.0384,0.0192,-0.2308,-0.4230,-0.7116,'25'
7794,-0.6696,-0.3730,0.1584,0.8910,1.0000,0.9762,0.9762,0.7684,0.4106,0.0154,...,0.0910,0.1818,0.2000,0.1454,0.0182,-0.2910,0.0728,0.0728,-0.5818,'25'
7795,-0.5764,-0.1764,0.5106,0.3742,-0.1670,-0.5858,-0.7882,-0.7224,-0.6330,-0.8212,...,0.4130,0.5870,0.4348,0.5652,0.3478,-0.0434,0.3044,-0.0434,-0.5000,'26'
7796,-0.6624,-0.3334,0.3666,0.4292,-0.2084,-0.5374,-0.4542,-0.6208,-0.6376,-0.5042,...,0.2520,0.2846,0.4146,0.3170,0.2520,-0.0244,-0.0894,-0.1708,-0.3170,'26'

In [8]:
X_data = data.iloc[: , :617]
Y_data = data.iloc[: , 617:]
Y_data

     class
0      '1'
1      '1'
2      '2'
3      '2'
4      '3'
...    ...
7792  '24'
7793  '25'
7794  '25'
7795  '26'
7796  '26'

[7797 rows x 1 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=42)
X_train

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f608,f609,f610,f611,f612,f613,f614,f615,f616,f617
5566,-0.1592,0.5770,0.6710,0.4674,-0.2532,-0.6502,-0.8486,-0.8852,-0.9426,-0.9164,...,0.0642,0.3028,0.2294,0.3578,0.2110,0.3762,0.3578,0.1010,0.0276,-0.0642
5875,-0.5078,0.0310,0.5906,0.9274,0.6684,0.2332,0.1502,-0.1398,-0.2642,-0.2850,...,0.3906,0.4062,0.5782,0.5312,0.6718,0.5624,0.3126,0.2812,0.4062,0.1406
5943,-0.5280,-0.3326,-0.0370,0.3564,0.8450,0.9500,0.7402,0.7544,0.8998,0.6686,...,-0.1930,0.1404,0.0878,0.1578,0.1052,0.2982,-0.2106,0.2632,0.1930,-0.0878
904,-0.2510,0.5362,0.5064,0.6808,0.6936,0.5234,0.5320,0.2978,0.2086,0.0042,...,0.5846,0.4616,0.1846,0.1846,-0.1384,-0.0154,-0.0462,0.0770,0.1230,-0.1846
1446,0.2682,1.0000,0.7272,0.5410,-0.1500,-0.4910,-0.6864,-0.3500,-0.4136,-0.6864,...,0.0732,-0.3008,-0.2846,-0.2196,-0.2520,-0.2520,-0.3170,0.1220,-0.1870,-0.3170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,-0.4236,0.1702,0.1752,0.5652,0.5378,0.7292,0.6448,0.2820,0.1354,0.1652,...,0.4382,0.3370,0.3146,0.3034,0.3596,0.1574,0.0562,-0.1460,-0.1012,-0.1910
5390,-0.4102,0.4102,0.4060,0.6966,0.5086,0.3760,0.0128,-0.1710,-0.4188,-0.4488,...,0.1334,-0.1834,-0.1500,-0.0166,0.0666,0.1500,0.1334,0.4166,0.7500,0.5000
860,-0.8888,0.2448,0.4286,0.4400,0.8164,1.0000,0.8526,0.6734,0.7030,0.4626,...,0.7044,0.6000,0.4260,0.7044,0.6696,0.2870,0.2000,0.1826,0.0434,-0.2348
7603,-0.6210,-0.4758,0.2016,0.4032,0.3468,-0.1130,-0.3952,-0.5322,-0.5888,-0.5888,...,0.4140,0.6178,0.3376,0.3248,0.3504,-0.0192,-0.0192,0.0192,0.0064,-0.2102
7270,-0.4840,-0.0032,0.5000,1.0000,0.8366,0.5192,0.5032,0.5834,0.7020,0.5994,...,0.5500,0.3500,0.4500,0.5000,0.4250,0.0750,0.0500,-0.0500,-0.0250,-0.5000

In [10]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_test

array([[0.2009    , 0.41392793, 0.66838801, ..., 0.75688125, 0.69502995,
        0.69963291],
       [0.0965    , 0.42343866, 0.49787363, ..., 0.74429839, 0.81639672,
        0.50852948],
       [0.2561    , 0.30370918, 0.50496152, ..., 0.57656443, 0.3770801 ,
        0.23731376],
       ...,
       [0.2198    , 0.37990067, 0.55710814, ..., 0.21447028, 0.25759929,
        0.10159793],
       [0.2959    , 0.3086759 , 0.62100041, ..., 0.4148972 , 0.5377191 ,
        0.44094148],
       [0.5159    , 0.681285  , 0.57006885, ..., 0.597798  , 0.57543821,
        0.09976247]])

In [11]:
clf = MLPClassifier(hidden_layer_sizes=20,learning_rate='adaptive',alpha=0.1)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Точность модели: {accuracy}')

C:\Users\Nikita\AppData\Roaming\Python\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Точность модели: 0.9301282051282052

C:\Users\Nikita\AppData\Roaming\Python\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [12]:
p = Perceptron(penalty='l1', alpha=0.0001)
p.fit(X_train, y_train)
y_pred = p.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Точность модели Perceptron: {accuracy}')

C:\Users\Nikita\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Точность модели Perceptron: 0.9288461538461539